[phases.setup]
# Install required system packages
nixpkgs = ["python311", "ffmpeg", "git"]

[phases.build]
# Optional: confirm ffmpeg installation during build
cmds = [
  "ffmpeg -version"
]

[phases.install]
# Install Python dependencies from requirements.txt
cmds = [
  "pip install --break-system-packages -r requirements.txt"
]

[phases.start]
# Start the FastAPI server using Uvicorn
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
